services:
  mcsli-docker:
    container_name: mcsli-docker
    image: ghcr.io/realsz27/mcsli:latest
    volumes:
      - ./config:/data/minecraft
    environment:
      - SERVER_SOFTWARE=purpur
      - SERVER_VERSION=1.21
      - MAX_RAM=1G
      - MIN_RAM=1G
    ports:
      - 25565:25565
