name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-21-jre-headless wget curl jq shellcheck

    - name: Run syntax check
      run: |
        shellcheck install.sh

    - name: Run script with validation
      env:
        CI_MODE: "true"
        SERVER_VERSION: "1.20.4"
        SERVER_SOFTWARE_CHOICE: "1"
        FIREWALL_CHOICE: "1"
        WEBUI_CHOICE: "n"
      run: |
        chmod +x ./install.sh
        ./install.sh --check

    - name: ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        ignore_paths: "" # Optional: paths to ignore when running ShellCheck
        ignore_names: "" # Optional: names to ignore when running ShellCheck
        severity: "warning" # Optional: minimum severity of errors to consider
        check_together: false # Optional: run shellcheck on all files at once, instead of one at a time
        scandir: "." # Optional: directory to be searched for files
        format: "gcc" # Optional: output format
        version: "stable" # Optional: specify a concrete version of ShellCheck to use
